"""init

Revision ID: edf36e180150
Revises: 
Create Date: 2023-08-23 10:43:12.223931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'edf36e180150'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_topics_id', table_name='topics')
    op.drop_index('ix_topics_name', table_name='topics')
    op.drop_table('topics')
    op.drop_index('ix_mediaitems_channel_id', table_name='mediaitems')
    op.drop_index('ix_mediaitems_id', table_name='mediaitems')
    op.drop_index('ix_mediaitems_topic_id', table_name='mediaitems')
    op.drop_table('mediaitems')
    op.drop_index('ix_channels_id', table_name='channels')
    op.drop_index('ix_channels_name', table_name='channels')
    op.drop_table('channels')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('isactive', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ispublic', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='channels_pkey')
    )
    op.create_index('ix_channels_name', 'channels', ['name'], unique=False)
    op.create_index('ix_channels_id', 'channels', ['id'], unique=False)
    op.create_table('mediaitems',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('size_MB', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('subtitle_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rtmp_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('small_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('small_rtmp_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hd_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hd_rtmp_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('history_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('geo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_new', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('channel', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('topic', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='mediaitems_pkey'),
    sa.UniqueConstraint('channel_id', 'topic_id', 'title', 'date', 'time', name='unique_mediaitem')
    )
    op.create_index('ix_mediaitems_topic_id', 'mediaitems', ['topic_id'], unique=False)
    op.create_index('ix_mediaitems_id', 'mediaitems', ['id'], unique=False)
    op.create_index('ix_mediaitems_channel_id', 'mediaitems', ['channel_id'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('isactive', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ispublic', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='topics_pkey')
    )
    op.create_index('ix_topics_name', 'topics', ['name'], unique=False)
    op.create_index('ix_topics_id', 'topics', ['id'], unique=False)
    # ### end Alembic commands ###
