"""add_ut_ov_variants

Revision ID: 8e1371d7360a
Revises: b40806645448
Create Date: 2026-07-01 09:01:06.906775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e1371d7360a'
down_revision: Union[str, None] = 'b40806645448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_series_detection_jobs_id'), table_name='series_detection_jobs')
    op.drop_index(op.f('ix_series_detection_jobs_source_video_id'), table_name='series_detection_jobs')
    op.drop_index(op.f('ix_series_detection_jobs_target_video_id'), table_name='series_detection_jobs')
    op.drop_table('series_detection_jobs')
    op.drop_index(op.f('ix_topics_id'), table_name='topics')
    op.drop_index(op.f('ix_topics_name'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_channels_id'), table_name='channels')
    op.drop_index(op.f('ix_channels_name'), table_name='channels')
    op.drop_table('channels')
    op.drop_index(op.f('ix_filmliste_import_events_id'), table_name='filmliste_import_events')
    op.drop_table('filmliste_import_events')
    op.add_column('mediaitems', sa.Column('url_video_ut', sa.String(), nullable=True))
    op.add_column('mediaitems', sa.Column('url_video_low_ut', sa.String(), nullable=True))
    op.add_column('mediaitems', sa.Column('url_video_hd_ut', sa.String(), nullable=True))
    op.add_column('mediaitems', sa.Column('url_video_ov', sa.String(), nullable=True))
    op.add_column('mediaitems', sa.Column('url_video_low_ov', sa.String(), nullable=True))
    op.add_column('mediaitems', sa.Column('url_video_hd_ov', sa.String(), nullable=True))
    op.add_column('mediaitems', sa.Column('url_video_ov_ut', sa.String(), nullable=True))
    op.add_column('mediaitems', sa.Column('url_video_low_ov_ut', sa.String(), nullable=True))
    op.add_column('mediaitems', sa.Column('url_video_hd_ov_ut', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mediaitems', 'url_video_hd_ov_ut')
    op.drop_column('mediaitems', 'url_video_low_ov_ut')
    op.drop_column('mediaitems', 'url_video_ov_ut')
    op.drop_column('mediaitems', 'url_video_hd_ov')
    op.drop_column('mediaitems', 'url_video_low_ov')
    op.drop_column('mediaitems', 'url_video_ov')
    op.drop_column('mediaitems', 'url_video_hd_ut')
    op.drop_column('mediaitems', 'url_video_low_ut')
    op.drop_column('mediaitems', 'url_video_ut')
    op.create_table('filmliste_import_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('full_import', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('media_item_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('media_item_diff_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('media_item_diff_new_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('media_item_diff_updated_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('media_item_diff_deleted_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('filmliste_import_events_pkey'))
    )
    op.create_index(op.f('ix_filmliste_import_events_id'), 'filmliste_import_events', ['id'], unique=False)
    op.create_table('channels',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('isactive', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ispublic', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('channels_pkey'))
    )
    op.create_index(op.f('ix_channels_name'), 'channels', ['name'], unique=True)
    op.create_index(op.f('ix_channels_id'), 'channels', ['id'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('isactive', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ispublic', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('topics_pkey'))
    )
    op.create_index(op.f('ix_topics_name'), 'topics', ['name'], unique=True)
    op.create_index(op.f('ix_topics_id'), 'topics', ['id'], unique=False)
    op.create_table('series_detection_jobs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('source_video_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('target_video_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('result_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('series_detection_jobs_pkey'))
    )
    op.create_index(op.f('ix_series_detection_jobs_target_video_id'), 'series_detection_jobs', ['target_video_id'], unique=False)
    op.create_index(op.f('ix_series_detection_jobs_source_video_id'), 'series_detection_jobs', ['source_video_id'], unique=False)
    op.create_index(op.f('ix_series_detection_jobs_id'), 'series_detection_jobs', ['id'], unique=False)
    # ### end Alembic commands ###
