"""added series

Revision ID: b40806645448
Revises: 2923f2b301a7
Create Date: 2023-09-07 10:05:08.777372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b40806645448'
down_revision: Union[str, None] = '2923f2b301a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mediaitems', sa.Column('episode_number', sa.Integer(), nullable=True))
    op.add_column('mediaitems', sa.Column('season_number', sa.Integer(), nullable=True))
    op.add_column('mediaitems', sa.Column('series_name', sa.String(), nullable=True))
    op.drop_index('mediaitems_search_idx', table_name='mediaitems', postgresql_using='gin')
    op.drop_column('mediaitems', 'search_vector')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mediaitems', sa.Column('search_vector', postgresql.TSVECTOR(), autoincrement=False, nullable=True))
    op.create_index('mediaitems_search_idx', 'mediaitems', ['search_vector'], unique=False, postgresql_using='gin')
    op.drop_column('mediaitems', 'series_name')
    op.drop_column('mediaitems', 'season_number')
    op.drop_column('mediaitems', 'episode_number')
    # ### end Alembic commands ###
